### ISSUE TITLE
Type error index.tsx line 75

### ISSUE THREAD

**Issue by kmosti** [frontarm/create-react-blog#4] opened 2019-01-08 20:32 UTC
The build fails to compile:

![image](https://user-images.githubusercontent.com/20144749/50857020-a076cc00-138c-11e9-96d1-ee7ad0b8c97b.png)

OS: macOS 10.14.2
Node/npm: v10.14.0 / 6.4.1

**Comment by jamesknelson** [comment] 2019-01-09 02:51
I'm not able to reproduce this on a fresh call to `npx create-react-blog test --typescript`, and then running `yarn start` in the console.

How are calling the build script? Also, can you confirm that your project is using TypeScript 3.2.2?

**Comment by kmosti** [comment] 2019-01-09 07:57
I have not actually touched anything, so yes Typescript is 3.2.2.
I also tried creating a new blog called test, and verified that yarn install runs with no issues.
I can ignore the compilation error (and the page renders fine) by just prepending
`// @ts-ignore`
However, not a great solution.

**Comment by jamesknelson** [comment] 2019-01-09 09:00
Weiiird. Any chance you could zip up the generated folder (including `node_modules`) and put it somewhere for me to take a look?

**Comment by kmosti** [comment] 2019-01-10 20:37
Here you go:

https://www.jottacloud.com/s/045a958fe90aefb4e1f9d6ec4d4774136b6

**Comment by jamesknelson** [comment] 2019-01-12 04:35
Thanks! I've tried diffing your node_modules against a newly installed node_modules, but it's basically the same. Given that your zip's source builds just fine, I assume the issue is something to do with your local TypeScript configuration or environment variables.

I'm going to close this for the moment, but feel free to re-open if you can reproduce on another machine.

**Closed by jamesknelson** 2019-01-12 04:35 UTC
